markdown: kramdown
title: Shadow.GA
email: shadowarmadyl@outlook.com
description: "Flarum is the next-generation forum software that makes online discussion fun. It's simple, fast, and free."
baseurl: ""
url: "https://shadow.ga"
twitter_username: ShadowGADev
google_analytics_id: UA-44566935-2
kramdown:
  input: GFM

collections:
  docs:
    output: true
