markdown: kramdown
title: Shadow.GA
email: webmaster@mg.shadow.ga
description: "We are a creative building server."
baseurl: "https://shadow.ga"
url: "https://shadow.ga"
twitter_username:  shadowgadev
google_analytics_id: UA-44566935-2
kramdown:
  input: GFM

collections:
  docs:
    output: true
